version: "3.7"
services:

  service1:
    container_name: nginx_service1
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./service1/:/var/www/
    networks:
      - envoymesh
    expose:
      - "80"
    ports:
      - "8010:80"

  service2:
    container_name: nginx_service2
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./service2/:/var/www/
    networks:
      - envoymesh
    expose:
      - "80"
    ports:
      - "8020:80"

networks:
  envoymesh: {}