version: "3"

services:
  ui-service:
    build:
      context: ui-service
    image: idzik/istio-ui-service:v2
    volumes:
      - ./ui-service/nginx-local.conf:/etc/nginx/conf.d/nginx.conf
      - ./ui-service/index.html:/var/www/index.html
    ports:
      - "80:80"
    networks:
      - quoteservice
  quote-service:
    build:
      context: quote-service
    image: idzik/istio-quote-service:v2
    volumes:
    - ./quote-service/server:/app/server
    ports:
    - "8080:8080"
    networks:
      - quoteservice

networks:
  quoteservice: {}